import json
import time
from enum import Enum
from typing import Any, Dict, Optional

class MessageType(Enum):
    PING = "PING"
    PONG = "PONG"
    DISCOVER = "DISCOVER"
    EDGE_LIST = "EDGE_LIST"
    REGISTER = "REGISTER"
    PREDICTION = "PREDICTION"
    STATE_UPDATE = "STATE_UPDATE"
    ROLLBACK = "ROLLBACK"

def now_ms() -> int:
    return int(time.time() * 1000)

def create_message(msg_type: str, client_id: str, seq: int, payload: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """
    msg_type: one of MessageType.*.value
    client_id: the logical ID of this client (string in Python; can be u8/u32 in Go if desired)
    seq: monotonically increasing sequence number generated by transport
    payload: type-specific body
    """
    return {
        "type": msg_type,
        "client_id": client_id,
        "seq": seq,
        "timestamp_ms": now_ms(),
        "payload": payload or {},
    }

# Encode message to bytes for UDP transport.
def encode_message(msg: Dict[str, Any]) -> bytes:
    return json.dumps(msg, separators=(",", ":"), ensure_ascii=False).encode("utf-8")

# Decode bytes back into a dict message. Errors propagate to caller.
def decode_message(data: bytes) -> Dict[str, Any]:
    return json.loads(data.decode("utf-8"))